services:
  refinery-db-migration:
    image: marcelaritonang/refinery:latest
    pull_policy: always
    container_name: refinery-db-migration
    command: ["migrate"]
    env_file:
      - .env
    restart: "no"
    networks:
      - internet

  refinery:
    image: marcelaritonang/refinery:latest
    pull_policy: always
    container_name: refinery
    ports:
      - 7003:7003
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      refinery-db-migration:
        condition: service_completed_successfully
    networks:
      - internet
    # volumes:
    #   - ./public/uploads:/app/public/uploads

networks:
  internet:
    name: internet
    external: true